In [1]:
import numpy
print(numpy.__version__)

2.0.2


In [2]:
import numpy as np
print(np.__version__)


# numpy provides the support for powerful data structure named as Array


arr = np.array([10,20,30,40,50])
print(arr)
print(type(arr))

2.0.2
[10 20 30 40 50]
<class 'numpy.ndarray'>


In [3]:
import time
numbers = list(range(1, 10000000))   # 1 2 3 4 5 6 7 8 ..........................99999
total = 0
start_time = time.time() # record start time
for n in numbers:
  total += n
end_time = time.time() # record end time
print("Total:", total)
print(f"Execution Time: {end_time - start_time:.4f} seconds") # .4f → means “show 4 digits after the decimal point

Total: 49999995000000
Execution Time: 1.8004 seconds


In [4]:
import time
numbers = np.arange(1, 10000000)
start_time = time.time()
total = np.sum(numbers)
end_time = time.time()
print("Total:", total)
print(f"Execution Time: {end_time - start_time:.4f} seconds")

Total: 49999995000000
Execution Time: 0.0113 seconds


In [5]:
# Array
# In programming, an array is a data structure used to store a collection of elemen
# or values, of the same data type under a single variable name.
# Array : Single Dimensional (1D) and Multi Dimensional (2D)
# How to create a 1D array
# array() used to create 1D or 2D array

arr = np.array([10,20,30,40,50,60])
print(arr)
print(type(arr))


[10 20 30 40 50 60]
<class 'numpy.ndarray'>


In [6]:
# shape property
# help us determine the dimensions of an array
# return (n,)
# for 1D array return (n,) where n is the number of elements
# for 2D array return (n,m) where n is the number of rows and m is the number of columns

arr = np.array([10,20,30,40,50,60])
print(arr.shape)

(6,)


In [7]:
# Create a 2D Array
twod = np.array([[1,2],[3,4],[5,6]])
print(twod)
print(twod.shape)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [8]:
twod = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(twod)
print(twod.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


In [9]:
# Indexin and slicing
arr = np.array([10,20,30,40,50,60,70,80,90])
print(arr[2])
print(arr[-1])
print(arr[:5])
print(arr[::5])

30
90
[10 20 30 40 50]
[10 60]


In [10]:
twod = np.array([[1,2,],[3,4,],[5,6]])
print(twod)
print(twod[0,1])
print(twod[2,0])
#show me 1st row
print(twod[0])
# show me 2nd column [for any specific column] arr[:,indexNumberOfThatColumn]

[[1 2]
 [3 4]
 [5 6]]
2
5
[1 2]


In [11]:
# dtype property
# help us determining the data type of an array

arr = np.array([10,20,30,40,50])
print (arr)
print(arr.dtype)  #64 bits = can store up to 64 digits

# 32 bits = can store up to 32 digits



[10 20 30 40 50]
int64


In [12]:
arr = np.array([10,20,30,40], dtype='i1') #1 ---> int every element to be of 1byte  [1byte = 8 bits]
print(arr.dtype)

int8


In [13]:
arr = np.array([10.1,20.2,30.3,40.4,])
print (arr.dtype)

float64


In [14]:
arr = np.array([True,False,True,False])
print (arr.dtype)

bool


In [15]:
arr = np.array(['apple','banana','cherry'])
print (arr.dtype)
# U ---> unicode string
# 6 -----> max length of a string

<U6


In [16]:
arr = np.array([10.1,20.2,30.3,40.4,],dtype='int')   #dtype='float'
print (arr.dtype)

int64


In [17]:
arr = np.array([10.1,20.2,30.3,40.4,],dtype='i')   #i --> float
print (arr.dtype)

int32


In [18]:
arr = np.array([10,20,30,40,],dtype='i')   #i1 int1Byte  (1Byte = 8 bits)
print (arr.dtype)

# i2 int2bytes  2bytes = 16bits  8+8
# i4 int2bytes  4bytes = 32bits  8+8+8+8
# i8 int8byes   8bytes = 64bits  8+8+8+8+8+8+8+8

int32


In [19]:
#age 1......150 can use 8bits
#marks 1...100 can use 8bits

In [20]:
# astype() used for conversion
arr = np.array([10.1,20.2,30.3,40.4,])
arr = arr.astype('i')
print(arr)
print(arr.dtype)

[10 20 30 40]
int32


In [21]:
#copy() and view
#COPYY

# a copy will create a new independent array in a diff memory location
# meaning if you make any changes in copied_array it won't effect original_array
org_arr = np.array([10,20,30,40,50])
copied_arr = org_arr.copy()
print(org_arr)
print(copied_arr)

[10 20 30 40 50]
[10 20 30 40 50]


In [22]:
#copy() and view
# (VIEWW)

# a view is the representation af original_array and it shares same memory location
# meaning if you make any changes in copis_array it will effect in orginal_array
org_arr = np.array([10,20,30,40,50])
copied_arr = org_arr.view()
print(org_arr)
print(copied_arr)

[10 20 30 40 50]
[10 20 30 40 50]


In [23]:
# copy() and view()

# copy()
# a copy will create a new independent array in a diff memory location
# meaning if you make any changes in copied_array it won't effect original_array

org_arr = np.array([10,20,30,40,50,60])
print(org_arr)

copied_arr = org_arr.copy()
print(copied_arr)

# let's make some changes in copied_arr
copied_arr[1] = 200
print(copied_arr)
print(org_arr)


[10 20 30 40 50 60]
[10 20 30 40 50 60]
[ 10 200  30  40  50  60]
[10 20 30 40 50 60]


In [24]:
org_arr = np.array([10,20,30,40,50,60])

print(org_arr)

# view()

# a view is the representation of original_array and it shares same memory location

# meaning if you make any changes in copied_array it will effect original_array

copied_arr = org_arr.view()

print(copied_arr)

# let's make some changes in copied_arr

copied_arr[1] = 200

print(copied_arr)

print(org_arr)


[10 20 30 40 50 60]
[10 20 30 40 50 60]
[ 10 200  30  40  50  60]
[ 10 200  30  40  50  60]


In [25]:
org_arr = np.array([10,20,30,40,50,60])
copied_arr = org_arr.view()
# shares_memory() --> return True if arrays are sharing same memory location
print(np.shares_memory(org_arr,copied_arr))

True


In [26]:
# NUmpy Array Reshaping  ---> Convert 1D --->2D     2D ---> 1D
# reshape()

# Convert 1D --->2D

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr.shape)   # 2x6  6x2  3x4  4x3  12x1  1x12

twod = arr.reshape(6,2)
print(twod.shape)
print(twod)

(12,)
(6, 2)
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [27]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,])
twod = arr.reshape(11,1)
print(twod.shape)
print(twod)

(11, 1)
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]]


In [28]:
# numpy.newaxis is used to increase the dimesion of the existing array by one more dimension
# meaning 1D array will become 2D array

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,])
# arr[np.newaxiaa,:]  #row vector
arr[:,np.newaxis]  # column vector



array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [29]:
# convert 2D into 1D
twod = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(twod)
print(twod.shape)

arr = twod.reshape(12)
print(arr.shape)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
(12,)
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [30]:
twod = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr = twod.reshape(-1)
print(arr.shape)
print(arr)

(12,)
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [31]:
twod = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr = twod.flatten()
print(arr.shape)
print(arr)

(12,)
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [32]:
# concatenate()
# used to join 2 Arrays

arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
arr = np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6 7 8]


In [33]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
arr = np.concatenate((arr1,arr2))
print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [34]:
# array_split()
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,])
np.array_split(arr,4)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10, 11])]

In [35]:
# sorting
# np.sort()   # sort the array in a ascending order
prices = np.array([78,34,56,90,102,34,12,67,34,120,172,95])
print(np.sort(prices))

[ 12  34  34  34  56  67  78  90  95 102 120 172]


In [36]:
# sorting
# np.sort()   # sort the array in a descending order
prices = np.array([78,34,56,90,102,34,12,67,34,120,172,95])
print(np.sort(prices)[::-1])

[172 120 102  95  90  78  67  56  34  34  34  12]


In [37]:
# Filter Operations In Numpy

arr = np.array([1,4,2,7,9,3,5,8])
print(arr)

for i in arr:    #in numpy dont need to use for loops
  if i>=5:
    print(i)

[1 4 2 7 9 3 5 8]
7
9
5
8


In [38]:
# boolean masking
res = arr>= 5
print(res)

[False False False  True  True False  True  True]


In [39]:
arr = np.array([1,4,2,7,9,3,5,8])
res = arr>=5
print(arr[res])

[7 9 5 8]


In [40]:
# np.where(exprsn)
# np.where returns IndexNunbers
arr = np.array([1,4,2,7,9,3,5,8])
res = np.where(arr>=5)
print(res)
print(arr[res])

(array([3, 4, 6, 7]),)
[7 9 5 8]


In [41]:
arr = np.array([10, 32, 30, 50, 20, 82, 91, 45])
# Find indices where value is 30
indices = np.where(arr == 30)
print(f"Indices where value is 30: {indices}")
# Find indices where values are even
even_indices = np.where(arr % 2 == 0)
print(f"Indices of even values: {even_indices}")
# Conditional selection
new_arr = np.where(arr > 40, arr * 2, arr)
print(f"Array after conditional selection: {new_arr}")
# if array more than 40 needs to multiply by 2 so the answer will be:
# [ 10  32  30 100  20 164 182  90]

Indices where value is 30: (array([2]),)
Indices of even values: (array([0, 1, 2, 3, 4, 5]),)
Array after conditional selection: [ 10  32  30 100  20 164 182  90]


In [42]:
# random module
from numpy import random
x = random.randint(100)    # 1 till 100
print(x)

82


In [43]:
x = random.randint(90,120)     # 90 till 120
print(x)

119


In [44]:
# rand()
# generate a float random value betwee n 0 and 1
# this float random number is float
x = random.rand()
print(x)

0.23724789983476235


In [45]:
x = random.randint(100,size=(10))
print(x)

[ 4 26 80 38 59 71 24 19 40 79]


In [46]:
x = random.randint(50,100,size=(4,5))
print(x)

[[93 88 69 81 71]
 [54 56 68 52 59]
 [92 75 55 64 60]
 [77 85 64 58 69]]


In [47]:
x = random.rand(10)
print(x)

[0.30629745 0.97489499 0.46279731 0.87037803 0.28546761 0.6110055
 0.92847925 0.44922456 0.18106891 0.78171226]


In [48]:
x = random.rand(3,5)
print(x)

[[0.79595528 0.49531721 0.36873813 0.77961603 0.36634506]
 [0.63537537 0.30852021 0.14560635 0.96303151 0.84784355]
 [0.24888531 0.15272794 0.83338677 0.44193985 0.18061869]]


In [49]:
# choice()
# random number
x= random.choice([5,6,7,8,11,14,15,9]) # random.randint(5,15)
print(x)

8


In [50]:
x = random.choice([5,6,7,8,11,14,15,9],size=(12))
print(x)

[ 8  5 11 15  5 14  7 14  5 11  7  5]


In [51]:
# zeros()
# it will create an arrays filled with all Zeros 0's
# defaulth data type will be float

arr = np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [52]:
arr = np.zeros((3,5))
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [53]:
x = np.array ([])
print(x)

[]


In [54]:
arr =np.zeros((3,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [55]:
arr =np.zeros((3,3),dtype='i')
print(arr)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [56]:
# ones()
# it will create an arrays filled with all 1's
# default data type will be Float

arr = np.ones(10,dtype='i')   # that's why we need to put 'i' at the back
print(arr)

[1 1 1 1 1 1 1 1 1 1]


In [57]:
# numpy.sim()
# used to compute the sum of all elements

x = np.random.randint(50,size=(10))
x

array([26,  3, 41, 47, 29, 26, 14, 28,  9, 31])

In [58]:
print(np.sum(x))

254


In [59]:
# mean() returns the average
print(np.mean(x))

25.4


In [60]:
# range()   # generate sequence of int numbes
# in numpy we called it arange
print(np.arange(11))  # starting from zero till x-1
print(np.arange(10,21))   # starting from x till y-1
print(np.arange(10,21,2))    # starting from zero till x-1 based on intervals


[ 0  1  2  3  4  5  6  7  8  9 10]
[10 11 12 13 14 15 16 17 18 19 20]
[10 12 14 16 18 20]


In [61]:
# np.unique()
# used to retrn uniqe elements as the sorted array
x = np.unique([1,2,3,1,4,5,25,4,6,7,4,3,8,9,1,31,12,7,15,10,14])
print(x)

# not duplicate the same unit
# unique is to remove the duplicate and put them in sequence
# unique elements has sorted in the list
# the data will be sorted


[ 1  2  3  4  5  6  7  8  9 10 12 14 15 25 31]


In [62]:
x = np.array([1,2,3,1,4,5,25,4,6,7,4,3,8,9,1,31,12,7,15,10,14])
np.unique(x,return_index=True)

# unique ---> [1 2 3 4 5 6 7 8 9 10 12 13 14 15
# index numbers  --->  0 1 2 4

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 12, 14, 15, 25, 31]),
 array([ 0,  1,  2,  4,  5,  8,  9, 12, 13, 19, 16, 20, 18,  6, 15]))

In [63]:
x = np.array([1,2,3,1,4,5,25,4,6,7,4,3,8,9,1,31,12,7,15,10,14])
for i in enumerate (x):
  print(i)

(0, np.int64(1))
(1, np.int64(2))
(2, np.int64(3))
(3, np.int64(1))
(4, np.int64(4))
(5, np.int64(5))
(6, np.int64(25))
(7, np.int64(4))
(8, np.int64(6))
(9, np.int64(7))
(10, np.int64(4))
(11, np.int64(3))
(12, np.int64(8))
(13, np.int64(9))
(14, np.int64(1))
(15, np.int64(31))
(16, np.int64(12))
(17, np.int64(7))
(18, np.int64(15))
(19, np.int64(10))
(20, np.int64(14))


In [64]:
x = np.array([1,2,3,1,4,5,2,5,4,6,7,4,3,8,9,13,12,7,15,10,14])
uv , i = np.unique(x,return_index=True)

# unique          -->  1  2  3  4  5  6  7  8   9  10 12 13 14 15
# index numbers   -->  0  1  2  4  5  9  10 13 14  19 16 15 20 18

print(uv)
print(i)

[ 1  2  3  4  5  6  7  8  9 10 12 13 14 15]
[ 0  1  2  4  5  9 10 13 14 19 16 15 20 18]


In [65]:
# argsort()   ---> reorder based on original appearance
uv[np.argsort(i)]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 13, 12, 15, 10, 14])

In [66]:
# Numpy Broadcasting
arr1 = np.array([7,6,4])
arr2 = np.array([3,5,1])
print(arr1*arr2)

[21 30  4]


In [67]:
# Let's try performing arithmetic operations b/w uncompatible shapes
# we cannot perform together
arr1 = np.array([7,6,4])
arr2 = np.array([3,5,1])
print(arr1*arr2)

[21 30  4]


In [68]:
# cases where there will be no broadcasting error
# if anyone of them is 1

arr1 = np.array([7,6,4])
arr2 = np.array([3])
print(arr1*arr2)

[21 18 12]


In [69]:
# shape property
# used to determine the dimensions of an array
# for 1d array return(n,) ----> where n is the number of elements
# for 2D array return (n,m) ---> where n is the number of row and m is the number of column

print(arr.shape)

(10,)
